### ISSUE TITLE
Startup problem refferencing 127.0.0.1 instead of mariadb

### ISSUE THREAD

**Issue by aritas1** [juanluisbaptiste/docker-otrs#10]
I had some weird startup behavior. The docker image "default" Config.pm defined `$Self->{'DatabaseHost'} = 'mariadb';` but i get an error in /var/log/httpd/error_log:
`-e: DBI connect('database=otrs;host=127.0.0.1;','otrs',...) failed: Can't connect to MySQL server on '127.0.0.1' (111) at /usr/sbin/../../Kernel/System/DB.pm line 202`

So the source of my problems (the system is calling `127.0.0.1` instead of `mariadb`) was the default OTRs configuration folder which was moved to /Kernel.

So i deleted the /Kernel copy and all system are up again. Somehow this folder don't get removed every time? I looked into the corresponding function check_host_mount_dir but i don't see how this works in the context.

**Comment by juanluisbaptiste** [comment]
Please post how you are starting the container.

**Comment by aritas1** [comment]
I use the docker-compose.yml template from the git repo. I had this problem a few weeks ago as i was playing with the image, somehow i managed to get it working without deleting the /Kernel folder. This time i updated the linux kernel and the server reboot crashed this container.

```
root@server /data/otrs # cat docker-compose.yml
otrs:
    image: juanluisbaptiste/otrs:latest
    expose:
    - "80"
    links:
    - mariadb:mariadb
    volumes_from:
    - data-otrs
    environment:
        OTRS_POSTMASTER_FETCH_TIME: 5
        OTRS_HOSTNAME: support.tld
        OTRS_ADMIN_EMAIL: support@tld
        OTRS_ORGANIZATION: "XYZ"
        OTRS_ROOT_PASSWORD: xxx
        MYSQL_ROOT_PASSWORD: xxx
        OTRS_DB_PASSWORD: xxx
        OTRS_NUMBER_GENERATOR: "AutoIncrement"
        OTRS_LANGUAGE: "de"

mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    expose:
    - "3306"
    volumes_from:
    - data
    environment:
        MYSQL_ROOT_PASSWORD: xxx

data:
    image: centos/mariadb:latest
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    - "/etc/localtime:/etc/localtime:ro"
    command: /bin/true
data-otrs:
    image: juanluisbaptiste/otrs:latest
    volumes:
    - ./volumes/config:/opt/otrs/Kernel
    - "./otrs/backup:/var/otrs/backups"
    - "/etc/localtime:/etc/localtime:ro"
    command: /bin/true
```
