### ISSUE TITLE
setting OTRS_BACKUP_ROTATION has no effect

### ISSUE THREAD

**Issue by rdxmb** [juanluisbaptiste/docker-otrs#96]
**Image and OTRS versions**

juanluisbaptiste/otrs:6.0.28

**env vars in kubernetes statefulset**
```
          env:
           - name: OTRS_DB_NAME
             value: otrs
           - name: OTRS_DB_HOST
             value: mariadb
           - name: OTRS_DB_USER
             value: otrs
           - name: OTRS_DB_PASSWORD
             value: XXXXXXXXXXXXXXXXXXX
           - name: MYSQL_ROOT_USER
             value: root
           - name: MYSQL_ROOT_PASSWORD
             value: XXXXXXXXXXXXXXXXXXXXXX
           - name: OTRS_ARTICLE_STORAGE_TYPE
             value: ArticleStorageFS
           - name: OTRS_SET_PERMISSIONS
             value: "skip-article-dir"
           - name: OTRS_NUMBER_GENERATOR
             value: "AutoIncrement"
           - name: OTRS_SENDMAIL_MODULE
             value: "SMTP"
           - name: OTRS_SMTP_SERVER
             value: 10.XX.0.XX
           - name: OTRS_SMTP_PORT
             value: "25"
           - name: OTRS_BACKUP_ROTATION
             value: "2"
           - name: OTRS_BACKUP_TYPE
             value: "fullbackup"
           - name: OTRS_BACKUP_TIME
             value: "18 19 * * *"
           - name: OTRS_DEBUG
             value: "yes"
           - name: TZ
             value: Etc/UTC
```

**Describe the issue**
Backup-files are not rotated as expected:

```
-rwxr-xr-x 1 root root 23G May 14 07:58 otrs-2020-05-14_04-00-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul  8 00:18 otrs-2020-07-07_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul  9 00:13 otrs-2020-07-08_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 10 00:04 otrs-2020-07-09_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 11 00:09 otrs-2020-07-10_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 12 00:11 otrs-2020-07-11_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 13 00:09 otrs-2020-07-12_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 14 00:10 otrs-2020-07-13_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 15 00:15 otrs-2020-07-14_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 16 00:10 otrs-2020-07-15_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 17 00:14 otrs-2020-07-16_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 18 00:21 otrs-2020-07-17_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 19 00:21 otrs-2020-07-18_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 20 00:15 otrs-2020-07-19_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 21 00:24 otrs-2020-07-20_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 22 00:21 otrs-2020-07-21_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 23 00:28 otrs-2020-07-22_19-18-fullbackup.tar.gz
-rwxr-xr-x 1 root root 23G Jul 24 00:18 otrs-2020-07-23_19-18-fullbackup.tar.gz
```

**Expected behavior**
Backup-files are rotated / deleted after 2 days.
